// NeerSetu_JJ (NeerSetu JalJeevan) Main Application Bootstrap
// Rural-First, Offline-First PWA with ESP32 TinyML & Lightweight Digital Twin

import './styles/main.css';
import './styles/rural.css';
import './styles/twin.css';
import './styles/tech.css';

import { AppHeader } from './components/header.js';
import { AppNavigation } from './components/navigation.js';
import { HomeView } from './components/homeView.js';
import { MonitorView } from './components/monitorView.js';
import { TwinView } from './components/twinView.js';
import { HistoryView } from './components/historyView.js';
import { OfflineCenter } from './components/offlineCenter.js';
import { HealthView } from './components/healthView.js';
import { TechView } from './components/techView.js';
import { QrModal } from './components/qrModal.js';
import { StageModal } from './components/stageModal.js';

import { localDb } from './db/localDb.js';
import { connectionManager } from './services/connectionManager.js';
import { syncService } from './services/syncService.js';
import { i18n } from './i18n/i18nEngine.js';
import { qrService } from './services/qrService.js';

class NeerSetuApp {
  constructor() {
    this.appRoot = document.getElementById('app');
    this.currentRoute = 'home';
    this.currentViewInstance = null;

    this.header = null;
    this.navigation = null;
    this.mainViewport = null;
    this.qrModal = null;
    this.stageModal = null;

    this.init().catch((err) => {
      console.error('[NeerSetuApp] Failed to initialize:', err);
      if (this.appRoot && !this.appRoot.hasChildNodes()) {
        this.appRoot.innerHTML = `
          <div style="color: #fff; padding: 2rem; text-align: center; font-family: sans-serif;">
            <h2>NeerSetu Initialization Notice</h2>
            <p style="color: #94a3b8;">${err?.message || err}</p>
            <button onclick="location.reload()" style="padding: 10px 20px; margin-top: 10px; background: #0284c7; color: #fff; border: none; border-radius: 6px; cursor: pointer;">Reload Application</button>
          </div>
        `;
      }
    });
  }

  async init() {
    // 1. Initialize IndexedDB
    await localDb.readyPromise;

    // 2. Setup DOM Containers
    this.setupLayout();

    // Deep-link support: a QR generated by NeerSetu carries ?system=... .
    // Identify that AquaSystem immediately when the PWA is opened on any device.
    const deepLinkedSystem = new URL(window.location.href).searchParams.get('system');
    if (deepLinkedSystem) {
      await qrService.identifySystem(deepLinkedSystem);
      // If this device has already been granted BLE access to the ESP32,
      // reconnect silently. First-time pairing still requires the browser's
      // user gesture for security.
      connectionManager.tryAutoReconnect?.().catch(() => {});
    }

    // 3. Modals
    this.qrModal = new QrModal((sysId) => {
      this.header.update();
      if (this.currentViewInstance?.loadProfile) {
        this.currentViewInstance.loadProfile();
      }
    });

    this.stageModal = new StageModal();

    // 4. Header & Bottom Navigation
    this.header = new AppHeader({
      onScanQr: () => this.qrModal.open(connectionManager.getActiveSystemId()),
      onNavigate: (route) => this.navigateTo(route),
      onLanguageChange: () => this.refreshCurrentView()
    });
    this.header.render(this.appRoot);

    // 5. Main Viewport
    this.mainViewport = document.createElement('main');
    this.mainViewport.className = 'main-content-viewport';
    this.mainViewport.id = 'main-viewport';
    this.appRoot.appendChild(this.mainViewport);

    // 6. Bottom Navigation
    this.navigation = new AppNavigation({
      onNavigate: (route) => this.navigateTo(route)
    });
    this.navigation.render(this.appRoot);

    // 7. Register Service Worker for true Offline-First PWA capabilities
    this.registerServiceWorker();

    // 8. Setup offline detection + auto-offline mode with user permission
    this.setupOfflineDetection();

    // 9. Initial Route
    this.navigateTo('home');
  }

  setupLayout() {
    this.appRoot.innerHTML = '';
  }

  setupOfflineDetection() {
    // When the device goes offline, prompt user then switch to offline mode
    window.addEventListener('offline', () => {
      syncService.setSimulatedOffline(false); // Real offline takes over, clear sim flag
      this.showOfflinePermissionBanner();
    });

    window.addEventListener('online', () => {
      this.hideOfflinePermissionBanner();
      syncService.triggerSync();
      this.showSyncRestoredToast();
    });
  }

  showOfflinePermissionBanner() {
    let banner = document.getElementById('auto-offline-banner');
    if (banner) return; // Already showing

    banner = document.createElement('div');
    banner.id = 'auto-offline-banner';
    banner.className = 'auto-offline-banner';
    banner.innerHTML = `
      <div class="auto-offline-icon">
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#f59e0b" stroke-width="2">
          <line x1="1" y1="1" x2="23" y2="23"/>
          <path d="M16.72 11.06A10.94 10.94 0 0 1 19 12.55"/>
          <path d="M5 12.55a10.94 10.94 0 0 1 5.17-2.39"/>
          <path d="M10.71 5.05A16 16 0 0 1 22.58 9"/>
          <path d="M1.42 9a15.91 15.91 0 0 1 4.7-2.88"/>
          <path d="M8.53 16.11a6 6 0 0 1 6.95 0"/>
          <line x1="12" y1="20" x2="12.01" y2="20"/>
        </svg>
      </div>
      <div class="auto-offline-text">
        <strong>Internet Disconnected</strong><br/>
        NeerSetu will continue monitoring locally via Bluetooth. Data is saved on your device.
      </div>
      <button class="auto-offline-ok-btn" id="btn-offline-ok">Continue in Offline Mode</button>
    `;
    document.body.appendChild(banner);

    document.getElementById('btn-offline-ok')?.addEventListener('click', () => {
      this.hideOfflinePermissionBanner();
      this.navigateTo('offline');
    });
  }

  hideOfflinePermissionBanner() {
    const banner = document.getElementById('auto-offline-banner');
    if (banner) {
      banner.style.opacity = '0';
      banner.style.transform = 'translateY(-100%)';
      setTimeout(() => banner.remove(), 300);
    }
  }

  showSyncRestoredToast() {
    let toast = document.getElementById('online-toast');
    if (toast) toast.remove();

    toast = document.createElement('div');
    toast.id = 'online-toast';
    toast.className = 'online-restored-toast';
    toast.innerHTML = `
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#10b981" stroke-width="2.5">
        <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/>
        <polyline points="22 4 12 14.01 9 11.01"/>
      </svg>
      <span>Back online — connection restored.</span>
    `;
    document.body.appendChild(toast);

    setTimeout(() => {
      toast.style.opacity = '0';
      setTimeout(() => toast.remove(), 400);
    }, 4000);
  }

  navigateTo(route) {
    if (this.currentViewInstance && this.currentViewInstance.unmount) {
      this.currentViewInstance.unmount();
    }

    this.currentRoute = route;
    this.navigation.setRoute(route);
    this.mainViewport.innerHTML = '';

    // Scroll to top upon navigation
    this.mainViewport.scrollTop = 0;

    switch (route) {
      case 'home':
        this.currentViewInstance = new HomeView({
          onNavigate: (r) => this.navigateTo(r),
          onScanQr: () => this.qrModal.open(connectionManager.getActiveSystemId())
        });
        break;

      case 'monitor':
        this.currentViewInstance = new MonitorView({
          onNavigate: (r) => this.navigateTo(r)
        });
        break;

      case 'twin':
        this.currentViewInstance = new TwinView({
          onStageClick: (stage, telem, badge) => this.stageModal.open(stage, telem, badge)
        });
        break;

      case 'history':
        this.currentViewInstance = new HistoryView();
        break;

      case 'offline':
        this.currentViewInstance = new OfflineCenter();
        break;

      case 'health':
        this.currentViewInstance = new HealthView();
        break;

      case 'tech':
        this.currentViewInstance = new TechView();
        break;

      default:
        this.currentViewInstance = new HomeView({
          onNavigate: (r) => this.navigateTo(r),
          onScanQr: () => this.qrModal.open(connectionManager.getActiveSystemId())
        });
        break;
    }

    this.currentViewInstance.mount(this.mainViewport);
  }

  refreshCurrentView() {
    if (this.currentViewInstance && this.currentViewInstance.render) {
      this.currentViewInstance.render();
    }
  }

  registerServiceWorker() {
    if (!('serviceWorker' in navigator)) return;

    window.addEventListener('load', async () => {
      try {
        // Keep normal-browser installs healthy after app updates. We never
        // touch IndexedDB/local telemetry; only stale service-worker caches
        // are replaced when a newer worker is available.
        const registration = await navigator.serviceWorker.register('./sw.js', { updateViaCache: 'none' });
        await registration.update().catch(() => {});
        console.log('[NeerSetu PWA] ServiceWorker ready:', registration.scope);
      } catch (error) {
        console.warn('[NeerSetu PWA] ServiceWorker unavailable; app remains usable online:', error);
      }
    });
  }
}

// Bootstrap once DOM is ready
document.addEventListener('DOMContentLoaded', () => {
  window.neersetuApp = new NeerSetuApp();
});
